[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
blake2 = "0.10.6"
futures-util = "0.3.31"
ipnet = "2.11.0"
rtnetlink = "0.18.1"
tokio = { version = "1.48.0", features = ["full"] }
wireguard-control = "1.7.1"
