[workspace]
members = ["client", "server", "shared"]
resolver = "3"

[workspace.dependencies]
cat4igp-shared = { path = "shared" }
cat4igp-client = { path = "client" }
cat4igp-server = { path = "server" }
chrono = { version = "0.4.42", features = ["serde"] }
